config/routes.rb
Rails.application.routes.draw do
  devise_for :migrations
get 'books/search'
devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
#route to all relvant views within the books folder
 resources :books, only: [:index, :show, :search, :new, :create, :edit, :destroy]

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
#this is the model page for the books. A book has to belog to a user and category
#but the category does not need to have books
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/migration.rb
class Migration < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :zxcvbnable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
#Note: "books" technically can be legal associations or online resources
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    #user needs to be signed in before those pages are show
    #defines index page
    def index
        #index function.  #if no category is selected, then it dispalys all books, 
        #or all books that meet search parameters
		if params[:category].blank?
            @books = Book.all.order("created_at DESC")
             @q = Book.ransack(params[:q])
             @books = @q.result(distinct: true)
		else # if book category matches category selected, then it is displayed
			@category_id = Category.find_by(name: params[:category]).id
            @books = Book.where(:category_id => @category_id).order("created_at DESC")
        end
        
    end
    def search 
        @q = Book.ransack(params[:q])
        @books = @q.result(distinct: true)
    end
   def show
        
    end
   def new #creates a book, that belongs to a user and a category
		@book = current_user.books.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]

		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end
    def destroy #for removing a particular book
		@book.destroy
		redirect_to root_path
    end
    
    def edit #categories have a name and id. so the book has the category id in a variables
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    def update
        if @book.update(book_params) #if book is updated successfully, show the books page
            redirect_to book_path(@book)
        
        else 
        render 'edit' #otherwise go to edit page again
        end
    end

    private
        def book_params #the book object can be created and added to database with just the title,
            # but can have other variables attached as well
            params.require(:book, :title).permit(:category_id,:description, :author, :links)
        end
        def find_book 
            current_user = User.find(session[:user_id])
            current_user.books.find(params[:id])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<!--For for adding a new  resource -->
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= f.input :title, label: "Title of Resource" %>
<div class="form-group">
   <%= f.input :description, label: "Description" %>
  </div>
	<%= f.input :author, label: "Authors\\Organization"%>
    <%= f.input :links, label: "Links" %>
	<div class = "category-id" >
	 <label for="category-id">Category</label>
	 <%= select_tag(:category_id, options_for_select(@categories)) %>
	 </div>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/books/edit.html.erb
  
<!--This is accessed from each books' show page-->
<!--It should have the information previously saved showing-->
<h2><%= @book.title %> </h2>
	<div class="edit-book-form">

		<h1>Edit Book</h1>

		<%= simple_form_for @book, :html => { :multipart => true } do |f| %>

			<%= f.input :title, label: "Book Title" %>
			<%= f.input :author %>
            <%= f.input :links %>

			<%= f.select :category_id, @categories %>
			
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>
<% if @books.count == 0 %>
	<h1>There are no books currently in this category</h1>
<% else %>	
	<div class="row">
		<% @books.each do |book| %>
		<div class = "book">
		<!--Once clicked, directs the user to the book page-->
         <%= link_to book.title, book_path(book) %> 
         </div>   
		<% end %>
	</div>
<% end %>	
		<!--Once clicked, directs the user to the add book page-->
<%= link_to "Add Resource", new_book_path %>
<%= link_to "Search", books_search_path %>

app/views/books/new.html.erb
<h1> New Book</h1>
<%= render 'form' %>

app/views/books/search.html.erb
<!--Creates search view page-->
<!--USer can searrch a specific variable for their input-->
<h1> Search<h1>
    <%= search_form_for @q do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title_cont, class: 'form-control' %>
    <%= f.label "Author\\Organization" %>
    <%= f.text_field :author_cont, class: 'form-control' %>
    <%= f.label :description %>
    <%= f.text_field :description_cont, class: 'form-control' %>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/books/show.html.erb
<!--This controls what is showed for each book action-->
<h2><%= @book.title %> </h2>
<h3><%= @book.author %> </h2>
<h4>Category: <%=@book.category.name %></h4>
<p><%= @book.description %> </p>
<p><%= @book.links %>
 </div>
<% if user_signed_in? %>
    <% if @book.user_id = current_user.id %>
        <div class="col-xs-1">
        <%= button_to 'Edit', edit_book_path(@book), :class =>"btn btn-custom" %>
        </div>
        <div class="col-xs-0">
        <%= button_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" },  :class => "btn btn-custom" %>
        </div>
        <% end %>
        </div>
<% end %>
<div class="btn btn-custom col-xs-3">
<%=link_to 'Back', 'javascript:history.back()' %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Immigration Library</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  </head>


  <body>
    <%= render 'partials/navbar' %>
      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
     <!---This is the page for the nav bar. Depending on what the user clicks,
      it directs it to the page for that action -->
<nav class="navbar navbar-nav navbar-fixed-top">
<div class = "container">
 <div class="nav navbar-nav navbar-left">
    <a class="navbar-brand" href="/">
      <%= link_to image_tag("white_logo.png", :size => "40x40", alt:"Immigration Library Home"), root_path %> 
    </a> </li>
 </div>
  <ul class="nav navbar-nav navbar-left">
 	<li><%= link_to "Immigration Library", root_path, class: "navbar_brand" %> </li>
 </ul>
  <!--gets logo, set it to that size-->
   <ul class="nav navbar-nav ml-auto w-100 justify-content-end">

      <li><%= link_to "Search", books_search_path %> </li>
         <% if user_signed_in? %>
          	<li><%= link_to "Add Resource", new_book_path %></li>
          <% end %>
      <!--Builds dropdown for categories-->
      <li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="dropdownMenuLink" aria-labelledby="dropdownMenu">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
						<% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, books_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>
        
    </ul>
<!--What is displayed here depends on whether or not the user is logged in-->
<ul class = "nav navbar-nav navbar-right">
    <% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>    
		<% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>	
					<li><%= link_to "Log In", new_user_session_path %></li>
		<% end %>
  </ul>

          
   </div>
	</nav>
  </html>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>